'use no-plugins';

/* eslint-disable import/no-extraneous-dependencies, import/no-unresolved */

// Do not edit this file manually, it is auto-generated by catalyst-pluginizr

import '@test/test2/register-plugins';
import '@test/test3/register-plugins';
